"""RiseNext pure domain model — entities, value objects, domain events, policies. No I/O.

Enforced by the "Domain is pure" import contract: this package may not import
SQLAlchemy, FastAPI, Redis, httpx, LangChain, Taskiq or any vendor SDK. The one
third-party dependency is `phonenumbers`, which is pure computation — E.164
correctness for an India-first dialler is a domain invariant, not infrastructure.
"""

from rn_domain import events, policies
from rn_domain.entities import (
    Agent,
    AgentToolConfig,
    AgentVersion,
    AuditLogEntry,
    Call,
    CallEvent,
    CallToolExecution,
    Campaign,
    CampaignContact,
    ConsentRecord,
    Contact,
    DeadLetterJob,
    KnowledgeBase,
    Lead,
    Organization,
    OrganizationMember,
    OutboxEvent,
    Role,
    Suppression,
    User,
)
from rn_domain.enums import (
    AgentStatus,
    AgentVersionStatus,
    CallDirection,
    CallEndReason,
    CallStatus,
    CampaignContactStatus,
    CampaignStatus,
    ConsentSource,
    ConsentStatus,
    ContactStatus,
    LeadQualification,
    LeadStatus,
    OrganizationStatus,
    OutboxStatus,
    SuppressionReason,
    SuppressionScope,
    ToolExecutionStatus,
)
from rn_domain.identifiers import (
    AgentId,
    AgentVersionId,
    AuditLogId,
    CallEventId,
    CallId,
    CampaignContactId,
    CampaignId,
    ConsentRecordId,
    ContactId,
    DeadLetterJobId,
    KnowledgeBaseId,
    LeadId,
    OrganizationId,
    OutboxEventId,
    RoleId,
    SuppressionId,
    ToolExecutionId,
    UserId,
)
from rn_domain.permissions import ALL_PERMISSIONS, ORG_PERMISSIONS, PLATFORM_PERMISSIONS, Permission
from rn_domain.values import LanguageTag, PhoneNumber

__version__ = "0.1.0"

__all__ = [
    "ALL_PERMISSIONS",
    "ORG_PERMISSIONS",
    "PLATFORM_PERMISSIONS",
    "Agent",
    "AgentId",
    "AgentStatus",
    "AgentToolConfig",
    "AgentVersion",
    "AgentVersionId",
    "AgentVersionStatus",
    "AuditLogEntry",
    "AuditLogId",
    "Call",
    "CallDirection",
    "CallEndReason",
    "CallEvent",
    "CallEventId",
    "CallId",
    "CallStatus",
    "CallToolExecution",
    "Campaign",
    "CampaignContact",
    "CampaignContactId",
    "CampaignContactStatus",
    "CampaignId",
    "CampaignStatus",
    "ConsentRecord",
    "ConsentRecordId",
    "ConsentSource",
    "ConsentStatus",
    "Contact",
    "ContactId",
    "ContactStatus",
    "DeadLetterJob",
    "DeadLetterJobId",
    "KnowledgeBase",
    "KnowledgeBaseId",
    "LanguageTag",
    "Lead",
    "LeadId",
    "LeadQualification",
    "LeadStatus",
    "Organization",
    "OrganizationId",
    "OrganizationMember",
    "OrganizationStatus",
    "OutboxEvent",
    "OutboxEventId",
    "OutboxStatus",
    "Permission",
    "PhoneNumber",
    "Role",
    "RoleId",
    "Suppression",
    "SuppressionId",
    "SuppressionReason",
    "SuppressionScope",
    "ToolExecutionId",
    "ToolExecutionStatus",
    "User",
    "UserId",
    "events",
    "policies",
]
