"""Declarative base, metadata conventions and shared column types.

Three things here matter more than they look:

**The naming convention.** Postgres auto-names constraints and indexes when you
do not, and those names differ between an autogenerated migration and a
hand-written one. That makes `downgrade` unreliable — you cannot drop a
constraint whose name you cannot predict. Naming everything explicitly is what
makes the migration round-trip in the Phase-1 definition of done actually work.

**Timestamps are `timestamptz`, always.** There is no naive column in this
schema and there never will be. The Python side is enforced by ruff's `DTZ`
rules; this is the storage half.

**`TenantOwnedBase` puts the tenant key in the type system.** Every tenant-owned
table inherits it, so `TenantScopedRepository[ModelT]` can be bound to something
that provably *has* an `organization_id`. Without that the repository would be
reaching for an attribute the type checker cannot see, and the tenant predicate —
the thing the whole isolation story rests on — would be unverifiable.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, MetaData, Uuid, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column

__all__ = [
    "METADATA",
    "Base",
    "TenantOwnedBase",
    "created_at_column",
    "enum_check",
    "json_column",
    "nullable_organization_fk",
    "utc_timestamp",
]

# Explicit, predictable constraint names. `%(constraint_name)s` is used for CHECK
# so that a named CheckConstraint keeps its name rather than being mangled.
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

METADATA = MetaData(naming_convention=NAMING_CONVENTION)


class Base(DeclarativeBase):
    """Declarative base for every ORM model.

    ORM models are **persistence structures, not domain objects**. They hold no
    business logic and no invariants beyond what the database enforces; the
    domain entity in `rn_domain` is the thing with rules. Each model exposes
    `to_domain()` / `from_domain()` and nothing else of consequence.
    """

    metadata = METADATA

    #: **Every `datetime` column is `timestamptz`.**
    #:
    #: SQLAlchemy's default for a bare `Mapped[datetime]` is `TIMESTAMP WITHOUT
    #: TIME ZONE`, so a column declared without an explicit type silently becomes
    #: naive — and then a timezone-aware Python value fails to insert, or worse,
    #: a naive one succeeds and the offset is lost. Mapping it here makes
    #: "timestamptz, always, no exceptions" a property of the base class rather
    #: than something every column declaration has to remember.
    #:
    #: `test_schema_invariants.py` asserts no naive timestamp column exists, so a
    #: future override cannot reintroduce one quietly.
    type_annotation_map = {  # noqa: RUF012
        datetime: DateTime(timezone=True),
    }

    #: UUID primary key, generated by the application (`rn_core.ids.new_id`,
    #: UUIDv7). The server default is a safety net for rows inserted by hand
    #: during an incident; normal writes always supply the id, because the domain
    #: needs an entity's identity before anything is flushed.
    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )

    def __repr__(self) -> str:
        # Deliberately id-only. A default repr on a model holding a phone number
        # or a transcript is a leak waiting for the first exception that
        # includes it.
        return f"<{type(self).__name__} id={self.id}>"


class TenantOwnedBase(Base):
    """Base for tables owned by exactly one organization.

    `organization_id` is denormalised onto **every** tenant-owned table,
    including children that could reach it through a parent (DATA_MODEL §4.1).
    That is deliberate: a repository that forgets a join is precisely the bug
    being defended against, and a local column makes the tenant predicate
    trivially always present. The denormalisation is kept honest by composite
    foreign keys on the children, which make cross-tenant parentage structurally
    impossible rather than merely unlikely.

    `ON DELETE RESTRICT`: removing an organization must be a deliberate, ordered
    erasure, never a cascade that silently deletes call history.
    """

    __abstract__ = True

    @declared_attr
    @classmethod
    def organization_id(cls) -> Mapped[uuid.UUID]:
        return mapped_column(
            Uuid(as_uuid=True),
            ForeignKey("organizations.id", ondelete="RESTRICT"),
            nullable=False,
        )


def nullable_organization_fk() -> Mapped[uuid.UUID | None]:
    """A nullable tenant key, where NULL has an explicit documented meaning.

    Used by `suppressions` (NULL = platform-wide), `outbox` and `audit_logs`
    (NULL = platform-level event), `dead_letter_jobs` (tenant unknown at failure
    time) and `roles` (NULL = platform catalog row). These tables are *not*
    tenant-owned, so they do not inherit `TenantOwnedBase` and cannot be reached
    through a tenant-scoped repository by accident.
    """
    return mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("organizations.id", ondelete="RESTRICT"),
        nullable=True,
    )


def utc_timestamp() -> Mapped[datetime]:
    """A required timezone-aware timestamp with no server default."""
    return mapped_column(DateTime(timezone=True), nullable=False)


def created_at_column() -> Mapped[datetime]:
    """Bookkeeping `created_at`.

    `now()` is acceptable here because this is metadata about the row, not a
    business fact. Business instants — when a call started, was answered, ended —
    are supplied by the application from measured clocks, because Postgres'
    `now()` is transaction-start time and the finalizing transaction begins well
    after the call actually ended.
    """
    return mapped_column(DateTime(timezone=True), nullable=False, server_default=text("now()"))


def enum_check(column: str, enum_cls: type[enum.StrEnum], name: str) -> CheckConstraint:
    """A CHECK constraint generated from a domain enum.

    Native Postgres enum types are avoided: they cannot be reordered, values
    cannot be removed, and `ALTER TYPE ... ADD VALUE` has awkward transaction
    rules. A CHECK can be replaced with `ADD CONSTRAINT ... NOT VALID` followed
    by `VALIDATE CONSTRAINT`, which never blocks writes.

    This generates the constraint for the *ORM metadata*. Migrations contain
    their own frozen literal copy — a historical migration must not change
    meaning because the application's enum changed later.
    """
    values = ", ".join(f"'{member.value}'" for member in enum_cls)
    return CheckConstraint(f"{column} IN ({values})", name=name)


def json_column(nullable: bool = False) -> Mapped[dict[str, Any]]:
    """A JSONB column defaulting to an empty object.

    JSONB is permitted only where the shape is genuinely open. The rule that
    keeps that honest: **nothing a dashboard filters or sorts on may live only in
    JSONB.** If you need to filter on it, promote it to a column in the same PR.
    """
    return mapped_column(JSONB, nullable=nullable, server_default=text("'{}'::jsonb"), default=dict)
