"""baseline schema

Revision ID: 0001
Revises:
Create Date: 2026-07-29 09:52:14.512000+00:00

Review checklist before merging:
  - Does `downgrade()` fully reverse `upgrade()`? The round-trip is tested.
  - Does any statement take a lock that would block writes on a live table?
    `CREATE INDEX` must be `CONCURRENTLY` (outside a transaction) on a hot table.
  - Are enum/permission CHECK values a FROZEN literal snapshot? A migration must
    never import a live application catalog — an old migration whose meaning
    changes when today's code changes is not a migration.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ---------------------------------------------------------------------------
# FROZEN SNAPSHOT -- the permission catalog as it stood when this migration was
# written.
#
# This is a literal on purpose. A migration must NEVER import
# `rn_domain.permissions`: an old migration whose meaning changes because
# today's application catalog changed is not a migration, it is a time bomb.
# Replaying history on a fresh database has to reproduce the schema that existed
# then, not the schema that would exist now.
#
# Adding a permission therefore requires a NEW migration that replaces this
# CHECK. `tests/integration/test_schema_invariants.py` compares the live
# constraint against `rn_domain.permissions.ALL_PERMISSIONS` and fails when a
# permission was added without one -- so the friction is enforced, not requested.
# ---------------------------------------------------------------------------
PERMISSIONS_SNAPSHOT_0001: tuple[str, ...] = (
    "org:agent:create",
    "org:agent:delete",
    "org:agent:publish",
    "org:agent:read",
    "org:agent:update",
    "org:analytics:read",
    "org:audit:read",
    "org:call:export",
    "org:call:read",
    "org:campaign:cancel",
    "org:campaign:create",
    "org:campaign:pause",
    "org:campaign:read",
    "org:campaign:start",
    "org:campaign:update",
    "org:consent:manage",
    "org:consent:read",
    "org:contact:create",
    "org:contact:delete",
    "org:contact:export",
    "org:contact:import",
    "org:contact:read",
    "org:contact:update",
    "org:integration:manage",
    "org:integration:read",
    "org:knowledge:create",
    "org:knowledge:delete",
    "org:knowledge:read",
    "org:knowledge:update",
    "org:lead:export",
    "org:lead:read",
    "org:lead:update",
    "org:member:invite",
    "org:member:read",
    "org:member:remove",
    "org:member:update",
    "org:organization:read",
    "org:organization:update",
    "org:suppression:manage",
    "org:suppression:read",
    "platform:audit:read",
    "platform:call:read",
    "platform:health:read",
    "platform:organization:create",
    "platform:organization:read",
    "platform:organization:suspend",
    "platform:organization:update",
    "platform:usage:read",
)


def _permission_check_sql() -> str:
    """`roles.permissions` must be a subset of the frozen catalog.

    `<@` is array containment: every element of `permissions` must appear in the
    snapshot. An empty array is trivially contained, which is correct -- a role
    with no permissions is useless but not malformed.
    """
    values = ", ".join(f"'{p}'" for p in PERMISSIONS_SNAPSHOT_0001)
    return f"permissions <@ ARRAY[{values}]::text[]"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("external_auth_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'archived')", name=op.f("ck_organizations_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("external_auth_id", name="uq_organizations_external_auth_id"),
        sa.UniqueConstraint("slug", name="uq_organizations_slug"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("external_auth_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.UniqueConstraint("external_auth_id", name="uq_users_external_auth_id"),
    )
    op.create_table(
        "agents",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'paused', 'archived')", name=op.f("ck_agents_status")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_agents_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
        sa.UniqueConstraint("organization_id", "id", name="uq_agents_organization_id_id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_agents_organization_id_name"),
    )
    op.create_index(
        "ix_agents_organization_id_created_at",
        "agents",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "audit_logs",
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column(
            "audit_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_logs_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_logs_action_created_at", "audit_logs", ["action", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_logs_actor_user_id_created_at",
        "audit_logs",
        ["actor_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_organization_id_created_at",
        "audit_logs",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "contacts",
        sa.Column("phone_e164", sa.String(length=20), nullable=False),
        sa.Column("phone_hash", sa.String(length=64), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint("phone_e164 LIKE '+%'", name=op.f("ck_contacts_phone_e164_format")),
        sa.CheckConstraint(
            "status IN ('active', 'invalid_number', 'do_not_call')", name=op.f("ck_contacts_status")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_contacts_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
        sa.UniqueConstraint("organization_id", "id", name="uq_contacts_organization_id_id"),
        sa.UniqueConstraint(
            "organization_id", "phone_e164", name="uq_contacts_organization_id_phone_e164"
        ),
    )
    op.create_index(
        "ix_contacts_organization_id_created_at",
        "contacts",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_contacts_organization_id_phone_hash",
        "contacts",
        ["organization_id", "phone_hash"],
        unique=False,
    )
    op.create_table(
        "dead_letter_jobs",
        sa.Column("task_name", sa.String(length=200), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint("attempt_count >= 0", name=op.f("ck_dead_letter_jobs_attempt_count")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_dead_letter_jobs_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dead_letter_jobs")),
    )
    op.create_index(
        "ix_dead_letter_jobs_failed_at", "dead_letter_jobs", ["failed_at"], unique=False
    )
    op.create_index(
        "ix_dead_letter_jobs_task_name_failed_at",
        "dead_letter_jobs",
        ["task_name", "failed_at"],
        unique=False,
    )
    op.create_table(
        "knowledge_bases",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_knowledge_bases_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_bases")),
        sa.UniqueConstraint("organization_id", "id", name="uq_knowledge_bases_organization_id_id"),
        sa.UniqueConstraint(
            "organization_id", "name", name="uq_knowledge_bases_organization_id_name"
        ),
    )
    op.create_table(
        "outbox",
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("aggregate_type", sa.String(length=64), nullable=True),
        sa.Column("aggregate_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint("attempt_count >= 0", name=op.f("ck_outbox_attempt_count")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_outbox_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox")),
    )
    op.create_index(
        "ix_outbox_unpublished",
        "outbox",
        ["created_at", "id"],
        unique=False,
        postgresql_where="published_at IS NULL",
    )
    op.create_table(
        "roles",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("permissions", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_roles_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
    )
    op.create_index(
        "uq_roles_org_key",
        "roles",
        ["organization_id", "key"],
        unique=True,
        postgresql_where="organization_id IS NOT NULL",
    )
    op.create_index(
        "uq_roles_platform_key",
        "roles",
        ["key"],
        unique=True,
        postgresql_where="organization_id IS NULL",
    )
    op.create_table(
        "suppressions",
        sa.Column("phone_hash", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("source_call_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "(scope = 'platform' AND organization_id IS NULL) OR (scope = 'organization' AND organization_id IS NOT NULL)",
            name=op.f("ck_suppressions_scope_organization"),
        ),
        sa.CheckConstraint(
            "reason IN ('user_request', 'regulator_dnd', 'complaint', 'bounced', 'manual')",
            name=op.f("ck_suppressions_reason"),
        ),
        sa.CheckConstraint(
            "scope IN ('organization', 'platform')", name=op.f("ck_suppressions_scope")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_suppressions_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppressions")),
    )
    op.create_index(
        "ix_suppressions_phone_hash_organization_id",
        "suppressions",
        ["phone_hash", "organization_id"],
        unique=False,
    )
    op.create_table(
        "agent_versions",
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("languages", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "voice_map",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "turn_policy",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "guardrail_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("realtime_model", sa.String(length=100), nullable=True),
        sa.Column("telephony_sample_rate", sa.Integer(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status <> 'published' OR published_at IS NOT NULL",
            name=op.f("ck_agent_versions_published_at"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')", name=op.f("ck_agent_versions_status")
        ),
        sa.CheckConstraint(
            "telephony_sample_rate IS NULL OR telephony_sample_rate IN (8000, 16000, 24000)",
            name=op.f("ck_agent_versions_telephony_sample_rate"),
        ),
        sa.CheckConstraint("version_number >= 1", name=op.f("ck_agent_versions_version_number")),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_agent_versions_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "agent_id"],
            ["agents.organization_id", "agents.id"],
            name="fk_agent_versions_organization_id_agent_id_agents",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_agent_versions_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_versions")),
        sa.UniqueConstraint(
            "agent_id", "version_number", name="uq_agent_versions_agent_id_version_number"
        ),
        sa.UniqueConstraint("organization_id", "id", name="uq_agent_versions_organization_id_id"),
    )
    op.create_index("ix_agent_versions_agent_id", "agent_versions", ["agent_id"], unique=False)
    op.create_table(
        "consent_records",
        sa.Column("phone_hash", sa.String(length=64), nullable=False),
        sa.Column("phone_e164", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("captured_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "source IN ('web_form', 'inbound_call', 'whatsapp', 'import', 'verbal_on_call', 'other')",
            name=op.f("ck_consent_records_source"),
        ),
        sa.CheckConstraint(
            "status <> 'revoked' OR revoked_at IS NOT NULL",
            name=op.f("ck_consent_records_revoked_at"),
        ),
        sa.CheckConstraint(
            "status IN ('granted', 'revoked', 'expired')", name=op.f("ck_consent_records_status")
        ),
        sa.ForeignKeyConstraint(
            ["captured_by_user_id"],
            ["users.id"],
            name=op.f("fk_consent_records_captured_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "contact_id"],
            ["contacts.organization_id", "contacts.id"],
            name="fk_consent_records_organization_id_contact_id_contacts",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_consent_records_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consent_records")),
    )
    op.create_index(
        "ix_consent_records_organization_id_phone_hash",
        "consent_records",
        ["organization_id", "phone_hash", "captured_at"],
        unique=False,
    )
    op.create_index(
        "ix_consent_records_phone_hash_captured_at",
        "consent_records",
        ["phone_hash", "captured_at"],
        unique=False,
    )
    op.create_table(
        "leads",
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("qualification", sa.String(length=32), nullable=False),
        sa.Column("requested_service", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("source_call_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "qualification IN ('unknown', 'interested', 'not_interested', 'follow_up', 'not_eligible')",
            name=op.f("ck_leads_qualification"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'qualified', 'disqualified', 'converted', 'lost')",
            name=op.f("ck_leads_status"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "contact_id"],
            ["contacts.organization_id", "contacts.id"],
            name="fk_leads_organization_id_contact_id_contacts",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_leads_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
        sa.UniqueConstraint("organization_id", "id", name="uq_leads_organization_id_id"),
    )
    op.create_index("ix_leads_contact_id", "leads", ["contact_id"], unique=False)
    op.create_index(
        "ix_leads_organization_id_status_created_at",
        "leads",
        ["organization_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "organization_members",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_members_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_organization_members_role_id_roles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_organization_members_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_members")),
    )
    op.create_index(
        "ix_organization_members_user_id", "organization_members", ["user_id"], unique=False
    )
    op.create_index(
        "uq_organization_members_active",
        "organization_members",
        ["organization_id", "user_id"],
        unique=True,
        postgresql_where="deleted_at IS NULL",
    )
    op.create_table(
        "agent_tool_configs",
        sa.Column("agent_version_id", sa.Uuid(), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "agent_version_id"],
            ["agent_versions.organization_id", "agent_versions.id"],
            name="fk_agent_tool_configs_org_id_agent_version_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_agent_tool_configs_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_tool_configs")),
        sa.UniqueConstraint(
            "agent_version_id", "tool_name", name="uq_agent_tool_configs_version_tool"
        ),
    )
    op.create_table(
        "agent_version_knowledge_bases",
        sa.Column("agent_version_id", sa.Uuid(), nullable=False),
        sa.Column("knowledge_base_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "agent_version_id"],
            ["agent_versions.organization_id", "agent_versions.id"],
            name="fk_avkb_organization_id_agent_version_id_agent_versions",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "knowledge_base_id"],
            ["knowledge_bases.organization_id", "knowledge_bases.id"],
            name="fk_avkb_organization_id_knowledge_base_id_knowledge_bases",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_agent_version_knowledge_bases_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_version_knowledge_bases")),
        sa.UniqueConstraint(
            "agent_version_id", "knowledge_base_id", name="uq_avkb_version_knowledge_base"
        ),
    )
    op.create_table(
        "campaigns",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("agent_version_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("scheduled_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_concurrent_calls", sa.Integer(), nullable=False),
        sa.Column("max_attempts_per_contact", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'scheduled', 'running', 'paused', 'completed', 'cancelled')",
            name=op.f("ck_campaigns_status"),
        ),
        sa.CheckConstraint("max_attempts_per_contact >= 1", name=op.f("ck_campaigns_max_attempts")),
        sa.CheckConstraint("max_concurrent_calls >= 1", name=op.f("ck_campaigns_max_concurrent")),
        sa.ForeignKeyConstraint(
            ["organization_id", "agent_version_id"],
            ["agent_versions.organization_id", "agent_versions.id"],
            name="fk_campaigns_organization_id_agent_version_id_agent_versions",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_campaigns_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
        sa.UniqueConstraint("organization_id", "id", name="uq_campaigns_organization_id_id"),
    )
    op.create_index(
        "ix_campaigns_organization_id_status_created_at",
        "campaigns",
        ["organization_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "campaign_contacts",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_call_id", sa.Uuid(), nullable=True),
        sa.Column("excluded_reason", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status <> 'excluded' OR excluded_reason IS NOT NULL",
            name=op.f("ck_campaign_contacts_excluded_reason"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'eligible', 'in_flight', 'completed', 'failed', 'excluded')",
            name=op.f("ck_campaign_contacts_status"),
        ),
        sa.CheckConstraint("attempt_count >= 0", name=op.f("ck_campaign_contacts_attempt_count")),
        sa.ForeignKeyConstraint(
            ["organization_id", "campaign_id"],
            ["campaigns.organization_id", "campaigns.id"],
            name="fk_campaign_contacts_organization_id_campaign_id_campaigns",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "contact_id"],
            ["contacts.organization_id", "contacts.id"],
            name="fk_campaign_contacts_organization_id_contact_id_contacts",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_campaign_contacts_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_contacts")),
        sa.UniqueConstraint(
            "campaign_id", "contact_id", name="uq_campaign_contacts_campaign_contact"
        ),
        sa.UniqueConstraint(
            "organization_id", "id", name="uq_campaign_contacts_organization_id_id"
        ),
    )
    op.create_index(
        "ix_campaign_contacts_contact_id", "campaign_contacts", ["contact_id"], unique=False
    )
    op.create_index(
        "ix_campaign_contacts_due",
        "campaign_contacts",
        ["campaign_id", "next_attempt_at"],
        unique=False,
        postgresql_where="status IN ('pending', 'eligible')",
    )
    op.create_table(
        "calls",
        sa.Column("agent_version_id", sa.Uuid(), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("counterparty_phone_e164", sa.String(length=20), nullable=False),
        sa.Column("platform_phone_e164", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("campaign_contact_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("provider_call_sid", sa.String(length=128), nullable=True),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("end_reason", sa.String(length=32), nullable=True),
        sa.Column("languages", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "direction <> 'outbound' OR contact_id IS NOT NULL",
            name=op.f("ck_calls_outbound_requires_contact"),
        ),
        sa.CheckConstraint("direction IN ('inbound', 'outbound')", name=op.f("ck_calls_direction")),
        sa.CheckConstraint(
            "end_reason IS NULL OR end_reason IN ('caller_hung_up','agent_ended','opt_out','provider_disconnect','max_duration','error')",
            name=op.f("ck_calls_end_reason"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'dialing', 'ringing', 'in_progress', 'completed', 'failed', 'no_answer', 'busy', 'cancelled')",
            name=op.f("ck_calls_status"),
        ),
        sa.CheckConstraint(
            "answered_at IS NULL OR started_at IS NULL OR answered_at >= started_at",
            name=op.f("ck_calls_answered_after_started"),
        ),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0", name=op.f("ck_calls_duration")
        ),
        sa.CheckConstraint(
            "ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at",
            name=op.f("ck_calls_ended_after_started"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "agent_version_id"],
            ["agent_versions.organization_id", "agent_versions.id"],
            name="fk_calls_organization_id_agent_version_id_agent_versions",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "campaign_contact_id"],
            ["campaign_contacts.organization_id", "campaign_contacts.id"],
            name="fk_calls_organization_id_campaign_contact_id_campaign_contacts",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "contact_id"],
            ["contacts.organization_id", "contacts.id"],
            name="fk_calls_organization_id_contact_id_contacts",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_calls_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calls")),
        sa.UniqueConstraint("organization_id", "id", name="uq_calls_organization_id_id"),
        sa.UniqueConstraint("provider", "provider_call_sid", name="uq_calls_provider_sid"),
    )
    op.create_index("ix_calls_campaign_contact_id", "calls", ["campaign_contact_id"], unique=False)
    op.create_index("ix_calls_contact_id", "calls", ["contact_id"], unique=False)
    op.create_index(
        "ix_calls_organization_id_queued_at",
        "calls",
        ["organization_id", "queued_at"],
        unique=False,
    )
    op.create_index(
        "ix_calls_organization_id_status_queued_at",
        "calls",
        ["organization_id", "status", "queued_at"],
        unique=False,
    )
    op.create_index(
        "ix_calls_unreconciled",
        "calls",
        ["queued_at"],
        unique=False,
        postgresql_where="status NOT IN ('completed','failed','no_answer','busy','cancelled')",
    )
    op.create_table(
        "call_events",
        sa.Column("call_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "call_id"],
            ["calls.organization_id", "calls.id"],
            name="fk_call_events_organization_id_call_id_calls",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_call_events_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_call_events")),
    )
    op.create_index(
        "ix_call_events_call_id_occurred_at",
        "call_events",
        ["call_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "call_tool_executions",
        sa.Column("call_id", sa.Uuid(), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "arguments",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "result",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('succeeded', 'failed', 'denied', 'timed_out')",
            name=op.f("ck_call_tool_executions_status"),
        ),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0", name=op.f("ck_call_tool_executions_duration")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "call_id"],
            ["calls.organization_id", "calls.id"],
            name="fk_call_tool_executions_organization_id_call_id_calls",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_call_tool_executions_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_call_tool_executions")),
    )
    op.create_index(
        "ix_call_tool_executions_call_id_started_at",
        "call_tool_executions",
        ["call_id", "started_at"],
        unique=False,
    )
    op.create_index(
        "ix_call_tool_executions_organization_id_tool_name_status",
        "call_tool_executions",
        ["organization_id", "tool_name", "status"],
        unique=False,
    )
    # ### end Alembic commands ###

    # -----------------------------------------------------------------------
    # Hand-written additions. Alembic autogenerates none of these: it does not
    # reflect array-containment CHECKs, it does not know about triggers, and the
    # `leads -> calls` constraint has to be added out of table-creation order.
    # -----------------------------------------------------------------------

    # `leads.source_call_id` points at the call the lead came out of. It is added
    # here rather than inside CREATE TABLE because `leads` is created before
    # `calls`, and it is composite so a lead can never cite another tenant's call
    # as its source. ON DELETE SET NULL: erasing a call under retention must not
    # take the commercial opportunity with it.
    op.execute(
        """
        ALTER TABLE leads
            ADD CONSTRAINT fk_leads_organization_id_source_call_id_calls
            FOREIGN KEY (organization_id, source_call_id)
            REFERENCES calls (organization_id, id)
            ON DELETE SET NULL
        """
    )

    # A role may only grant permissions from the frozen catalog above. Without
    # it, an invented or typo'd permission string is storable, and every
    # authorization check against that string silently never matches.
    #
    # Raw SQL rather than `op.create_check_constraint`, because the metadata
    # naming convention would be applied on the way in *and* again on the way
    # out, producing `ck_roles_ck_roles_permissions_catalog` on drop. Spelling
    # the name once, literally, keeps upgrade and downgrade symmetrical.
    op.execute(
        "ALTER TABLE roles ADD CONSTRAINT ck_roles_permissions_catalog "
        f"CHECK ({_permission_check_sql()})"
    )

    # An agent version is immutable once published. Enforced in the database
    # rather than by convention, because "which configuration served this call"
    # must stay answerable even if a future code path forgets the rule. Only
    # `status` and `published_at` may change after publication: archiving is
    # legitimate, rewriting behaviour is not.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION agent_versions_freeze() RETURNS trigger AS $$
        BEGIN
            IF OLD.published_at IS NOT NULL AND (
                   NEW.instructions           IS DISTINCT FROM OLD.instructions
                OR NEW.languages              IS DISTINCT FROM OLD.languages
                OR NEW.voice_map              IS DISTINCT FROM OLD.voice_map
                OR NEW.turn_policy            IS DISTINCT FROM OLD.turn_policy
                OR NEW.guardrail_config       IS DISTINCT FROM OLD.guardrail_config
                OR NEW.realtime_model         IS DISTINCT FROM OLD.realtime_model
                OR NEW.telephony_sample_rate  IS DISTINCT FROM OLD.telephony_sample_rate
                OR NEW.agent_id               IS DISTINCT FROM OLD.agent_id
                OR NEW.version_number         IS DISTINCT FROM OLD.version_number
                OR NEW.organization_id        IS DISTINCT FROM OLD.organization_id
            ) THEN
                RAISE EXCEPTION
                    'agent_versions.% is immutable after publication', OLD.id;
            END IF;
            RETURN NEW;
        END $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER agent_versions_freeze_trigger
        BEFORE UPDATE ON agent_versions
        FOR EACH ROW EXECUTE FUNCTION agent_versions_freeze();
        """
    )

    # -----------------------------------------------------------------------
    # Role ownership: a membership may reference a role only if the role is a
    # platform catalog role (`organization_id IS NULL`) or belongs to the same
    # organization as the membership.
    #
    # This is a trigger and not a composite foreign key because
    # `roles.organization_id` is nullable and no declarative constraint covers
    # both cases: MATCH SIMPLE is skipped whenever the referencing column is
    # NULL (so a forged NULL bypasses it), and MATCH FULL rejects NULLs outright
    # (so platform roles become unassignable). Splitting `roles` into two tables
    # would express it declaratively at the cost of a branch in every read.
    #
    # Enforcing it here means it holds for every writer — services, repositories,
    # raw SQL, a psql session during an incident — instead of only for callers
    # that remember. Authorization integrity must not depend on discovering
    # corrupt membership data later, when a context happens to be built.
    # -----------------------------------------------------------------------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION organization_members_role_scope() RETURNS trigger AS $$
        DECLARE
            role_org uuid;
        BEGIN
            SELECT organization_id INTO role_org FROM roles WHERE id = NEW.role_id;
            IF role_org IS NOT NULL AND role_org <> NEW.organization_id THEN
                RAISE EXCEPTION
                    'role % belongs to organization %, not %',
                    NEW.role_id, role_org, NEW.organization_id;
            END IF;
            RETURN NEW;
        END $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER organization_members_role_scope_trigger
        BEFORE INSERT OR UPDATE ON organization_members
        FOR EACH ROW EXECUTE FUNCTION organization_members_role_scope();
        """
    )

    # The trigger above validates a membership against the role's owner at write
    # time. Re-homing a role afterwards would invalidate memberships that were
    # legal when written, so a role's owner is immutable: change the role's
    # permissions, or create a new role, but never move one between tenants.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION roles_owner_immutable() RETURNS trigger AS $$
        BEGIN
            IF NEW.organization_id IS DISTINCT FROM OLD.organization_id THEN
                RAISE EXCEPTION
                    'roles.organization_id is immutable (role %)', OLD.id;
            END IF;
            RETURN NEW;
        END $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER roles_owner_immutable_trigger
        BEFORE UPDATE ON roles
        FOR EACH ROW EXECUTE FUNCTION roles_owner_immutable();
        """
    )


def downgrade() -> None:
    # Hand-written additions come off first, in reverse order.
    op.execute("DROP TRIGGER IF EXISTS roles_owner_immutable_trigger ON roles")
    op.execute("DROP FUNCTION IF EXISTS roles_owner_immutable()")
    op.execute(
        "DROP TRIGGER IF EXISTS organization_members_role_scope_trigger "
        "ON organization_members"
    )
    op.execute("DROP FUNCTION IF EXISTS organization_members_role_scope()")
    op.execute("DROP TRIGGER IF EXISTS agent_versions_freeze_trigger ON agent_versions")
    op.execute("DROP FUNCTION IF EXISTS agent_versions_freeze()")
    op.execute("ALTER TABLE roles DROP CONSTRAINT IF EXISTS ck_roles_permissions_catalog")
    op.execute(
        "ALTER TABLE leads DROP CONSTRAINT IF EXISTS "
        "fk_leads_organization_id_source_call_id_calls"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_call_tool_executions_organization_id_tool_name_status",
        table_name="call_tool_executions",
    )
    op.drop_index("ix_call_tool_executions_call_id_started_at", table_name="call_tool_executions")
    op.drop_table("call_tool_executions")
    op.drop_index("ix_call_events_call_id_occurred_at", table_name="call_events")
    op.drop_table("call_events")
    op.drop_index(
        "ix_calls_unreconciled",
        table_name="calls",
        postgresql_where="status NOT IN ('completed','failed','no_answer','busy','cancelled')",
    )
    op.drop_index("ix_calls_organization_id_status_queued_at", table_name="calls")
    op.drop_index("ix_calls_organization_id_queued_at", table_name="calls")
    op.drop_index("ix_calls_contact_id", table_name="calls")
    op.drop_index("ix_calls_campaign_contact_id", table_name="calls")
    op.drop_table("calls")
    op.drop_index(
        "ix_campaign_contacts_due",
        table_name="campaign_contacts",
        postgresql_where="status IN ('pending', 'eligible')",
    )
    op.drop_index("ix_campaign_contacts_contact_id", table_name="campaign_contacts")
    op.drop_table("campaign_contacts")
    op.drop_index("ix_campaigns_organization_id_status_created_at", table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_table("agent_version_knowledge_bases")
    op.drop_table("agent_tool_configs")
    op.drop_index(
        "uq_organization_members_active",
        table_name="organization_members",
        postgresql_where="deleted_at IS NULL",
    )
    op.drop_index("ix_organization_members_user_id", table_name="organization_members")
    op.drop_table("organization_members")
    op.drop_index("ix_leads_organization_id_status_created_at", table_name="leads")
    op.drop_index("ix_leads_contact_id", table_name="leads")
    op.drop_table("leads")
    op.drop_index("ix_consent_records_phone_hash_captured_at", table_name="consent_records")
    op.drop_index("ix_consent_records_organization_id_phone_hash", table_name="consent_records")
    op.drop_table("consent_records")
    op.drop_index("ix_agent_versions_agent_id", table_name="agent_versions")
    op.drop_table("agent_versions")
    op.drop_index("ix_suppressions_phone_hash_organization_id", table_name="suppressions")
    op.drop_table("suppressions")
    op.drop_index(
        "uq_roles_platform_key", table_name="roles", postgresql_where="organization_id IS NULL"
    )
    op.drop_index(
        "uq_roles_org_key", table_name="roles", postgresql_where="organization_id IS NOT NULL"
    )
    op.drop_table("roles")
    op.drop_index(
        "ix_outbox_unpublished", table_name="outbox", postgresql_where="published_at IS NULL"
    )
    op.drop_table("outbox")
    op.drop_table("knowledge_bases")
    op.drop_index("ix_dead_letter_jobs_task_name_failed_at", table_name="dead_letter_jobs")
    op.drop_index("ix_dead_letter_jobs_failed_at", table_name="dead_letter_jobs")
    op.drop_table("dead_letter_jobs")
    op.drop_index("ix_contacts_organization_id_phone_hash", table_name="contacts")
    op.drop_index("ix_contacts_organization_id_created_at", table_name="contacts")
    op.drop_table("contacts")
    op.drop_index("ix_audit_logs_organization_id_created_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor_user_id_created_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_action_created_at", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("ix_agents_organization_id_created_at", table_name="agents")
    op.drop_table("agents")
    op.drop_table("users")
    op.drop_table("organizations")
    # ### end Alembic commands ###
